[profile.default]
optimizer_runs = 200
via_ir = false
ffi = true
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
base = "${BASE_RPC_URL}"

baseSepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
baseSepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

[profile.default.fuzz]
runs = 100
seed = "0x4444"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.ci.fuzz]
runs = 1000

[profile.ci]
fuzz_runs = 100000
solc = "./bin/solc-static-linux"